version: "3.8"

services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
