version: "3.8"

services:
  frontend:
    image: ml-frontend
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
      - 3000:3000

  backend:
    image: ml-backend
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  training:
    image: ml-training
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - files:/src/imgs
      - model:/src/model

volumes:
  model:
  files:
